"""add tenders table

Revision ID: 8bd370cb6d28
Revises: 8ab6f197f7ed
Create Date: 2026-02-22 15:48:26.538928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd370cb6d28'
down_revision: Union[str, Sequence[str], None] = '8ab6f197f7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_tender_id'), 'tenders', ['tender_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_tender_id'), table_name='tenders')
    op.drop_table('tenders')
    # ### end Alembic commands ###
